default_job = "check"

[jobs.check]
command = [
    "cargo", "clippy",
    "--color", "always",
]
need_stdout = false

[jobs.check-all]
command = [
    "cargo", "clippy",
    "--all-targets",
    "--color", "always",
]
need_stdout = false

[jobs.test]
command = [
    "cargo", "nextest", "run",
    "--color", "always",
]
need_stdout = true

[jobs.doc]
command = [
    "cargo", "doc",
    "--color", "always",
    "--no-deps",
]
need_stdout = false

[jobs.doc-open]
command = [
    "cargo", "doc",
    "--color", "always",
    "--no-deps",
    "--open",
]
need_stdout = false
on_success = "back"

[jobs.run]
command = [
    "cargo", "run",
    "--color", "always",
]
need_stdout = true
allow_warnings = true
background = true

[keybindings]
c = "job:check"
