name: Publish

on:
  push:
    tags:
      - "**"

permissions:
  contents: read

jobs:
  cargo:
    uses: majksa-actions/workflows/.github/workflows/rust-publish.yml@v1
    secrets:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
